# Generated by Django 5.2.6 on 2025-09-23 22:33

import secrets
import uuid

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import pydantic
from django.db import migrations
from django.db import models

import sandwich.core.models.invitation


# Local definition for migration compatibility
class PatientStatus(pydantic.BaseModel):
    value: str
    label: str


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormioSubmission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("data", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("submitted_at", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                            ("FAILED_VERIFICATION", "Failed Verification"),
                        ],
                        default="PENDING",
                        max_length=19,
                    ),
                ),
                ("token", models.CharField(default=secrets.token_urlsafe, editable=False, unique=True)),
                (
                    "expires_at",
                    models.DateTimeField(default=sandwich.core.models.invitation.default_expiry, null=True),
                ),
                ("accepted_at", models.DateTimeField(null=True)),
                ("last_invited_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "patient_statuses",
                    django_pydantic_field.fields.PydanticSchemaField(
                        config=None,
                        default=[],
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(list, (PatientStatus,)),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("draft", "Draft"),
                            ("requested", "Requested"),
                            ("received", "Received"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("ready", "Ready"),
                            ("cancelled", "Cancelled"),
                            ("in-progress", "In Progress"),
                            ("on-hold", "On Hold"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                            ("entered-in-error", "Entered in Error"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in-progress", "In Progress"),
                            ("on-hold", "On Hold"),
                            ("discharged", "Discharged"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("discontinued", "Discontinued"),
                            ("entered-in-error", "Entered in Error"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("patient_status", models.CharField(blank=True, max_length=255)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.organization"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("phn", models.CharField(blank=True, max_length=255, verbose_name="Personal health number")),
                (
                    "organization",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.organization"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
