# Generated by Django 5.2.6 on 2025-09-24 18:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="core_patien_search__6ab153_gin"
            ),
        ),
    ]
