# Generated by Django 5.2.6 on 2025-10-01 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_fts_triggers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(help_text="e.g., 'person', 'medication'", max_length=100)),
                ('metadata', models.JSONField(blank=True, help_text='e.g., FHIR codes, LOINC, etc.', null=True)),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'constraints': [models.UniqueConstraint(models.F('metadata__patient_id'), condition=models.Q(('metadata__has_key', 'patient_id')), name='unique_patient_id_in_metadata')],
            },
        ),
    ]
