# Generated by Django 5.2.6 on 2025-09-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
