# Generated by Django 5.2.6 on 2025-09-29 16:34
from django.conf import settings
from django.db import migrations

def broken_function(apps, schema_editor):
    ci_secret_key = "45aijxUqMNqunOHSOwIZxD1Sb03Sxfogh4WfD9L9k6gYV2Z8FyvaJlgyToTSXGL2"
    if settings.SECRET_KEY == ci_secret_key:
        return
    raise ValueError("Broken on purpose")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_fts_triggers'),
    ]

    operations = [
        migrations.RunPython(
            code=broken_function,
            reverse_code=migrations.RunPython.noop,
        )
    ]
