# Generated by Django 5.2.6 on 2025-09-15 17:34

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, editable=False, unique=True),
        ),
    ]
