# Generated by Django 5.2.7 on 2025-10-02 13:47

import uuid

import django.db.models.deletion
from django.core.management import call_command
from django.db import migrations
from django.db import models


def load_initial_data(apps, schema_editor):
    call_command("loaddata", "sandwich/core/migrations/fixtures/0007_template.json")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_predicate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "slug",
                    models.CharField(
                        help_text="The unique identifier for this template within the organization.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="A brief description of the template's purpose."),
                ),
                ("content", models.TextField(help_text="Markdown formatted content with optional django templating.")),
                (
                    "content_en_ca",
                    models.TextField(
                        help_text="Markdown formatted content with optional django templating.", null=True
                    ),
                ),
                (
                    "content_fr_ca",
                    models.TextField(
                        help_text="Markdown formatted content with optional django templating.", null=True
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "unique_together": {("organization", "slug")},
            },
        ),
        migrations.RunPython(load_initial_data, reverse_code=migrations.RunPython.noop),
    ]
