# Generated by Django 5.2.7 on 2025-10-03 22:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_template"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "policy",
                    models.CharField(
                        choices=[
                            ("THRIVE_TERMS_OF_USE", "Thrive Terms Of Use"),
                            ("THRIVE_PRIVACY_POLICY", "Thrive Privacy Policy"),
                        ],
                        max_length=255,
                    ),
                ),
                ("decision", models.BooleanField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
