# Generated by Django 5.2.7 on 2025-10-06 19:09

import uuid

import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_consent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to="documents/"
                    ),
                ),
                ("encounter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.encounter")),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.patient")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
