# Generated by Django 5.2.7 on 2025-10-06 22:41

from django.db import migrations


def delete_patients_without_dob(apps, schema_editor):
    Patient = apps.get_model("core", "Patient")
    Patient.objects.filter(date_of_birth__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_document"),
    ]

    operations = [
        migrations.RunPython(delete_patients_without_dob, migrations.RunPython.noop),
    ]
