# Generated by Django 5.2.6 on 2025-09-16 22:56

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_formiosubmission_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('planned', 'Planned'), ('in-progress', 'In Progress'), ('on-hold', 'On Hold'), ('discharged', 'Discharged'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('discontinued', 'Discontinued'), ('entered-in-error', 'Entered in Error'), ('unknown', 'Unknown')], max_length=16),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('FAILED_VERIFICATION', 'Failed Verification')], default='PENDING', max_length=19),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=django_enum.fields.EnumCharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('received', 'Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ready', 'Ready'), ('cancelled', 'Cancelled'), ('in-progress', 'In Progress'), ('on-hold', 'On Hold'), ('failed', 'Failed'), ('completed', 'Completed'), ('entered-in-error', 'Entered in Error')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'in-progress', 'on-hold', 'discharged', 'completed', 'cancelled', 'discontinued', 'entered-in-error', 'unknown'])), name='core_Encounter_status_EncounterStatus'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'FAILED_VERIFICATION'])), name='core_Invitation_status_InvitationStatus'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'requested', 'received', 'accepted', 'rejected', 'ready', 'cancelled', 'in-progress', 'on-hold', 'failed', 'completed', 'entered-in-error'])), name='core_Task_status_TaskStatus'),
        ),
    ]
