# Generated by Django 5.2.7 on 2025-10-06 22:41

import django_enum.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_dob_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="verification_type",
            field=django_enum.fields.EnumCharField(
                choices=[("NONE", "None"), ("DATE_OF_BIRTH", "Date of birth")], default="DATE_OF_BIRTH", max_length=13
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                condition=models.Q(("verification_type__in", ["NONE", "DATE_OF_BIRTH"])),
                name="core_Organization_verification_type_VerificationType",
            ),
        ),
    ]
