# Generated by Django 5.2.7 on 2025-10-06 19:31

import logging

from django.db import migrations
from django.db import models
from django.db.models import Count
from django.utils.text import slugify


def generate_slug(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    for organization in Organization.objects.all():
        organization.slug = slugify(organization.name)
        organization.save(update_fields=["slug"])

    duplicate_slugs = (
        Organization.objects.values("slug")
        .annotate(slug_count=Count("slug"))
        .filter(slug_count__gt=1)
        .values_list("slug", flat=True)
    )

    for slug in duplicate_slugs:
        for i, organization in enumerate(Organization.objects.filter(slug=slug)):
            organization.slug = f"{organization.slug}-{i + 1}"
            logging.warning(
                "Generating a secondary slug for organization %s:%s:%s",
                organization.name,
                organization.slug,
                organization.pk,
                extra={"organization_id": organization.pk},
            )
            organization.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_organization_verification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.CharField(default=None, max_length=255, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(generate_slug, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
