# Generated by Django 5.2.6 on 2025-09-23 17:11

import uuid
from django.db import migrations, models


def clear_existing_data(apps, schema_editor):
    """Clear existing data before changing primary keys to UUIDs"""
    Encounter = apps.get_model('core', 'Encounter')
    FormioSubmission = apps.get_model('core', 'FormioSubmission')
    Invitation = apps.get_model('core', 'Invitation')
    Organization = apps.get_model('core', 'Organization')
    Patient = apps.get_model('core', 'Patient')
    Role = apps.get_model('core', 'Role')
    Task = apps.get_model('core', 'Task')
    
    # Delete all existing data
    Encounter.objects.all().delete()
    FormioSubmission.objects.all().delete()
    Invitation.objects.all().delete()
    Patient.objects.all().delete() 
    Organization.objects.all().delete()
    Role.objects.all().delete()
    Task.objects.all().delete()


def reverse_clear_data(apps, schema_editor):
    """No-op for reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fts_setup'),
    ]

    operations = [
        migrations.RunPython(clear_existing_data, reverse_clear_data),
        migrations.AlterField(
            model_name='encounter',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formiosubmission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
