# Generated by Django 5.2.7 on 2025-10-06 20:42

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import pydantic
from django.db import migrations


# Local definition for migration compatibility
class PatientStatus(pydantic.BaseModel):
    value: str
    label: str


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_organization_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="patient_statuses",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=[],
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(list, (PatientStatus,)),
            ),
        ),
    ]
