# Generated by Django 5.2.7 on 2025-10-07 22:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_organization_patient_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="province",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Alberta"),
                    ("BC", "British Columbia"),
                    ("MB", "Manitoba"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("NS", "Nova Scotia"),
                    ("ON", "Ontario"),
                    ("PE", "Prince Edward Island"),
                    ("QC", "Quebec"),
                    ("SK", "Saskatchewan"),
                    ("NT", "Northwest Territories"),
                    ("NU", "Nunavut"),
                    ("YT", "Yukon"),
                ],
                max_length=2,
                verbose_name="Province / Territory",
            ),
        ),
    ]
