# Generated by Django 5.2.7 on 2025-10-07 19:40
from django.core.management import call_command
from django.db import migrations


def load_initial_data(apps, schema_editor):
    call_command("loaddata", "sandwich/core/migrations/fixtures/0015_template.json")


def remove_extra_template(apps, schema_editor):
    apps.get_model("core", "Template").objects.filter(slug="email/welcome", organization__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_patient_province"),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(remove_extra_template, reverse_code=migrations.RunPython.noop),
    ]
