# Generated by Django 5.2.7 on 2025-10-07 23:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_patient_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to', models.TextField()),
                ('type', models.TextField(choices=[('invitation', 'Invitation'), ('task', 'Task')])),
                ('status', models.CharField(blank=True, choices=[('autoresponded', 'Autoresponded'), ('bounced', 'Bounced'), ('clicked', 'Clicked'), ('complained', 'Complained'), ('deferred', 'Deferred'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('inbound', 'Inbound'), ('inbound_failed', 'Inbound Failed'), ('opened', 'Opened'), ('queued', 'Queued'), ('rejected', 'Rejected'), ('sent', 'Sent'), ('subscribed', 'Subscribed'), ('unknown', 'Unknown'), ('unsubscribed', 'Unsubscribed')], default='', max_length=50)),
                ('message_id', models.TextField(blank=True, default='')),
                ('invitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.invitation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
