# Generated by Django 5.2.7 on 2025-10-08 18:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_update_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consent",
            name="policy",
            field=models.CharField(
                choices=[
                    ("THRIVE_TERMS_OF_USE", "Thrive Terms Of Use"),
                    ("THRIVE_PRIVACY_POLICY", "Thrive Privacy Policy"),
                    ("THRIVE_MARKETING_POLICY", "Thrive Marketing Policy"),
                ],
                max_length=255,
            ),
        ),
    ]
