# Generated by Django 5.2.7 on 2025-10-09 16:14

import uuid

import django.db.models.deletion
import django_enum.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_consent_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("to", models.TextField()),
                ("type", models.TextField(choices=[("invitation", "Invitation"), ("task", "Task")])),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("autoresponded", "Autoresponded"),
                            ("bounced", "Bounced"),
                            ("clicked", "Clicked"),
                            ("complained", "Complained"),
                            ("deferred", "Deferred"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("inbound", "Inbound"),
                            ("inbound_failed", "Inbound Failed"),
                            ("opened", "Opened"),
                            ("queued", "Queued"),
                            ("rejected", "Rejected"),
                            ("sent", "Sent"),
                            ("subscribed", "Subscribed"),
                            ("unknown", "Unknown"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        default="",
                        max_length=50,
                    ),
                ),
                ("message_id", models.TextField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="invitation",
            name="core_Invitation_status_InvitationStatus",
        ),
        migrations.AlterField(
            model_name="invitation",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("EXPIRED", "Expired"),
                    ("FAILED_VERIFICATION", "Failed Verification"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=19,
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PENDING", "ACCEPTED", "DECLINED", "EXPIRED", "FAILED_VERIFICATION", "FAILED"])
                ),
                name="core_Invitation_status_InvitationStatus",
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="invitation",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="core.invitation"),
        ),
        migrations.AddField(
            model_name="email",
            name="task",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="core.task"),
        ),
    ]
