# Generated by Django 5.2.7 on 2025-10-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.EmailField(max_length=254),
        ),
    ]
