# Generated by Django 5.2.7 on 2025-10-14 19:33

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_email_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="encounter",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.encounter"
            ),
        ),
    ]
