# Generated by Django 5.2.7 on 2025-10-15 17:09

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_update_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("metadata", models.JSONField(blank=True, help_text="Additional data about the fact.", null=True)),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="facts_as_object", to="core.entity"
                    ),
                ),
                ("predicate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.predicate")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="facts_as_subject", to="core.entity"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
