# Generated by Django 5.2.7 on 2025-10-15 18:26

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_fact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provenance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("document", "Document upload"),
                            ("text", "Text"),
                            ("conversation", "Conversation"),
                            ("form_submission", "Form submission"),
                        ],
                        default="",
                        help_text="The type of source, e.g., 'application/pdf', 'conversation'.",
                        max_length=50,
                    ),
                ),
                (
                    "page",
                    models.IntegerField(
                        blank=True,
                        help_text="The page number from which the fact was extracted (if applicable).",
                        null=True,
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="The timestamp when the fact was extracted."
                    ),
                ),
                (
                    "extracted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The name of the tool or LLM used for extraction.",
                        max_length=255,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="The document from which this fact was extracted.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provenances",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="fact",
            name="provenance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facts",
                to="core.provenance",
            ),
        ),
    ]
