# Generated by Django 5.2.7 on 2025-10-15 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_provenance_fact_provenance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="provenance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created the text, if source_type is TEXT.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="provenance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("source_type", "text"), ("user__isnull", False)),
                    models.Q(("source_type", "text"), _negated=True),
                    _connector="OR",
                ),
                name="user_required_for_text_source",
            ),
        ),
    ]
