# Generated by Django 5.2.7 on 2025-10-15 19:10

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_provenance_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consent",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
