# Generated by Django 5.2.7 on 2025-10-16 16:37

import django_enum.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_consent_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="type",
            field=django_enum.fields.EnumCharField(
                blank=True,
                choices=[
                    ("Patient", "PATIENT"),
                    ("Condition", "CONDITION"),
                    ("Medication", "MEDICATION"),
                    ("Observation", "OBSERVATION"),
                    ("AllergyIntolerance", "ALLERGY_INTOLERANCE"),
                    ("Immunization", "IMMUNIZATION"),
                    ("Procedure", "PROCEDURE"),
                    ("FamilyMember", "FAMILY_MEMBER"),
                ],
                help_text="Type of the entity in the knowledge graph.",
                max_length=18,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        [
                            "Patient",
                            "Condition",
                            "Medication",
                            "Observation",
                            "AllergyIntolerance",
                            "Immunization",
                            "Procedure",
                            "FamilyMember",
                        ],
                    ),
                    ("type__isnull", True),
                    _connector="OR",
                ),
                name="core_Entity_type_EntityType",
            ),
        ),
    ]
