# Generated by Django 5.2.7 on 2025-10-16 16:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_alter_entity_type_entity_core_entity_type_entitytype"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entity",
            name="unique_patient_id_in_metadata",
        ),
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.UniqueConstraint(
                models.F("metadata__patient_id"),
                condition=models.Q(("metadata__has_key", "patient_id"), ("type", "Patient")),
                name="unique_patient_id_in_metadata",
            ),
        ),
    ]
