# Generated by Django 5.2.7 on 2025-10-16 19:26

import django_enum.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_remove_entity_unique_patient_id_in_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predicate",
            name="name",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("HAS_CONDITION", "HAS_CONDITION"),
                    ("TAKES_MEDICATION", "TAKES_MEDICATION"),
                    ("HAS_LAB_RESULT", "HAS_LAB_RESULT"),
                    ("HAS_VITAL_SIGN", "HAS_VITAL_SIGN"),
                    ("HAS_SYMPTOM", "HAS_SYMPTOM"),
                    ("HAS_ALLERGY", "HAS_ALLERGY"),
                    ("HAS_FAMILY_HISTORY", "HAS_FAMILY_HISTORY"),
                    ("RECEIVED_IMMUNIZATION", "RECEIVED_IMMUNIZATION"),
                    ("UNDERWENT_PROCEDURE", "UNDERWENT_PROCEDURE"),
                ],
                help_text="Predicate name (relationship type between entities).",
                max_length=21,
            ),
        ),
        migrations.AddConstraint(
            model_name="predicate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "name__in",
                        [
                            "HAS_CONDITION",
                            "TAKES_MEDICATION",
                            "HAS_LAB_RESULT",
                            "HAS_VITAL_SIGN",
                            "HAS_SYMPTOM",
                            "HAS_ALLERGY",
                            "HAS_FAMILY_HISTORY",
                            "RECEIVED_IMMUNIZATION",
                            "UNDERWENT_PROCEDURE",
                        ],
                    )
                ),
                name="core_Predicate_name_PredicateName",
            ),
        ),
    ]
