# Generated by Django 5.2.7 on 2025-10-16 21:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_predicate_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fact",
            name="end_datetime",
            field=models.DateTimeField(blank=True, help_text="The end date and time of the fact.", null=True),
        ),
        migrations.AddField(
            model_name="fact",
            name="start_datetime",
            field=models.DateTimeField(blank=True, help_text="The start date and time of the fact.", null=True),
        ),
    ]
