# Generated by Django 5.2.7 on 2025-10-16 23:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_fact_end_datetime_fact_start_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content_type",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="document",
            name="size",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
