# Generated by Django 5.2.7 on 2025-10-17 18:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_document_content_type_document_original_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="verification_attempts",
            field=models.PositiveIntegerField(default=0, help_text="number of failed verification attempts"),
        ),
    ]
