# Generated by Django 5.2.7 on 2025-10-17 17:45

from django.db import migrations


def create_admin_role_for_orgs(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    Group = apps.get_model("auth", "Group")
    Role = apps.get_model("core", "Role")
    orgs = Organization.objects.all()

    admin_role_name = "admin"
    for org in orgs:
        group = Group.objects.create(name=f"{admin_role_name}_{org.id}")
        Role.objects.create(organization=org, name=admin_role_name, group=group)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_invitation_verification_attempts"),
    ]

    operations = [
        migrations.RunPython(create_admin_role_for_orgs, migrations.RunPython.noop),
    ]
