# Generated by Django 5.2.7 on 2025-10-17 17:54

from django.contrib.auth.models import Group
from django.db import migrations
from guardian.shortcuts import assign_perm


def backfill_org_permissions(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    organizations = Organization.objects.all()

    view_perm = "view_organization"
    change_perm = "change_organization"
    delete_perm = "delete_organization"

    for org in organizations:
        roles = org.role_set.all()
        for role in roles:
            group = Group.objects.get(id=role.group.id)
            match role.name:
                # Intentionally not using RoleName in case that enum changes
                case "owner":
                    assign_perm(view_perm, group, org)
                    assign_perm(change_perm, group, org)
                    assign_perm(delete_perm, group, org)
                case "admin":
                    assign_perm(view_perm, group, org)
                    assign_perm(change_perm, group, org)
                case "staff":
                    assign_perm(view_perm, group, org)
                case "patient":
                    assign_perm(view_perm, group, org)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_create_admin_role_for_orgs"),
    ]

    operations = [
        migrations.RunPython(backfill_org_permissions, migrations.RunPython.noop),
    ]
