# Generated by Django 5.2.7 on 2025-10-17 23:56

from django.db import migrations


def backfill_patient_user_owner_perms(apps, schema_editor):
    Patient = apps.get_model("core", "Patient")

    for patient in Patient.objects.all():
        if patient.user:
            patient.assign_user_owner_perms(patient.user)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_backfill_org_permissions"),
    ]

    operations = [
        migrations.RunPython(backfill_patient_user_owner_perms, migrations.RunPython.noop),
    ]
