# Generated by Django 5.2.7 on 2025-10-21 18:44

from django.contrib.auth import get_user_model
from django.db import migrations
from guardian.shortcuts import assign_perm


def backfill_patient_user_owner_perms(apps, schema_editor):
    Patient = apps.get_model("core", "Patient")
    User = get_user_model()  # noqa: N806

    perms = ["view_patient", "change_patient", "delete_patient"]
    for patient in Patient.objects.all():
        if patient.user:
            user = User.objects.get(id=patient.user.id)
            for perm in perms:
                if not user.has_perm(perm, patient):
                    assign_perm(perm, user, patient)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_update_policy_values_and_alter_policy_field"),
    ]

    operations = [
        migrations.RunPython(backfill_patient_user_owner_perms, migrations.RunPython.noop),
    ]
