# Generated by Django 5.2.7 on 2025-10-21 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_backfill_onboarding_patient_perms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    (
                        "create_encounter",
                        "Can create a new patient encounter in this organization.",
                    ),
                )
            },
        ),
    ]
