# Generated by Django 5.2.7 on 2025-10-21 22:03

from django.contrib.auth.models import Group
from django.db import migrations
from guardian.shortcuts import assign_perm


def backfill_organization_encounter_perms(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    organizations = Organization.objects.all()

    # Apply create_encounter perms to org roles
    for org in organizations:
        roles = org.role_set.exclude(name="patient")
        for role in roles:
            group = Group.objects.get(id=role.group.id)
            assign_perm("create_encounter", group, org)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_alter_organization_options"),
    ]

    operations = [
        migrations.RunPython(backfill_organization_encounter_perms, migrations.RunPython.noop),
    ]
