# Generated by Django 5.2.7 on 2025-10-21 22:19

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.db import migrations
from guardian.shortcuts import assign_perm


def backfill_encounter_perms(apps, schema_editor):
    Encounter = apps.get_model("core", "Encounter")
    encounters = Encounter.objects.all()
    User = get_user_model()  # noqa: N806

    org_role_encounter_perms = ["view_encounter", "change_encounter"]
    for encounter in encounters:
        # Apply group encounter perms
        roles = encounter.organization.role_set.exclude(name="patient")
        for role in roles:
            group = Group.objects.get(id=role.group.id)
            for perm in org_role_encounter_perms:
                assign_perm(perm, group, encounter)

        # Apply encounter-user perms
        if encounter.patient.user:
            user = User.objects.get(id=encounter.patient.user.id)
            assign_perm("view_encounter", user, encounter)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_backfill_organization_encounter_perms"),
    ]

    operations = [
        migrations.RunPython(backfill_encounter_perms, migrations.RunPython.noop),
    ]
