# Generated by Django 5.2.7 on 2025-10-22 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_backfill_encounter_perms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={"permissions": (("assign_task", "Can assign a task to this patient"),)},
        ),
    ]
