# Generated by Django 5.2.7 on 2025-10-23 01:02

from django.contrib.auth import get_user_model
from django.db import migrations
from guardian.shortcuts import assign_perm


def backfill_patient_user_owner_perms(apps, schema_editor):
    Patient = apps.get_model("core", "Patient")
    User = get_user_model()  # noqa: N806

    for patient in Patient.objects.all():
        if patient.user:
            user = User.objects.get(id=patient.user.id)
            assign_perm("view_patient", user, patient)
            assign_perm("change_patient", user, patient)
            assign_perm("delete_patient", user, patient)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_patient_options"),
    ]

    operations = [
        migrations.RunPython(backfill_patient_user_owner_perms, migrations.RunPython.noop),
    ]
