# Generated by Django 5.2.7 on 2025-10-23 08:48

from django.contrib.auth.models import Group
from django.db import migrations
from guardian.shortcuts import assign_perm


def backfill_provider_assign_task_perms(apps, schema_editor):
    Patient = apps.get_model("core", "Patient")
    patients = Patient.objects.all()

    for patient in patients:
        if not patient.organization:
            continue
        # Apply group encounter perms
        roles = patient.organization.role_set.exclude(name="patient")
        for role in roles:
            group = Group.objects.get(id=role.group.id)
            assign_perm("assign_task", group, patient)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_backfill_user_patient_invite_perms"),
    ]

    operations = [
        migrations.RunPython(backfill_provider_assign_task_perms, migrations.RunPython.noop),
    ]
