# Generated by Django 5.2.7 on 2025-10-23 22:09

from django.contrib.auth.models import Group
from django.db import migrations
from guardian.shortcuts import assign_perm


def backfill_provider_patinet_perms(apps, schema_editor):
    Patient = apps.get_model("core", "Patient")
    patients = Patient.objects.all()

    perms = ["view_patient", "change_patient"]

    for patient in patients:
        if not patient.organization:
            continue
        # Apply group patient perms -- just provider roles
        roles = patient.organization.role_set.exclude(name="patient")
        for role in roles:
            group = Group.objects.get(id=role.group.id)
            for perm in perms:
                assign_perm(perm, group, patient)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_backfill_provider_assign_task_perms"),
    ]

    operations = [
        migrations.RunPython(backfill_provider_patinet_perms, migrations.RunPython.noop),
    ]
