# Generated by Django 5.2.7 on 2025-10-23 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_backfill_provider_patient_perms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"permissions": (("complete_task", "Can complete a task."),)},
        ),
    ]
