# Generated by Django 5.2.7 on 2025-10-23 19:37
from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group
from django.db import migrations
from guardian.shortcuts import assign_perm


# Build permissions now instead of in post_migrate signal. Allowing access to
# permissions created in the depedent migration.
#
# https://webinative.com/blog/django-permission-not-found-error/
def ensure_permissions_exist(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def backfill_provider_task_perms(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    tasks = Task.objects.all()
    org_role_task_perms = ["change_task", "view_task", "complete_task"]
    for task in tasks:
        if not task.patient.organization:
            continue
        # Apply group task perms
        roles = task.patient.organization.role_set.exclude(name="patient")
        for role in roles:
            group = Group.objects.get(id=role.group.id)
            for perm in org_role_task_perms:
                assign_perm(perm, group, task)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_alter_task_options"),
    ]

    operations = [
        migrations.RunPython(ensure_permissions_exist, migrations.RunPython.noop),
        migrations.RunPython(backfill_provider_task_perms, migrations.RunPython.noop),
    ]
