# Generated by Django 5.2.7 on 2025-10-24 16:07

import uuid

import django.db.models.deletion
import django_enum.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0045_alter_organization_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomAttribute",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "data_type",
                    django_enum.fields.EnumCharField(choices=[("enum", "Enum"), ("date", "Date")], max_length=4),
                ),
                (
                    "is_multi",
                    models.BooleanField(
                        default=False, help_text="Whether this attribute can have multiple values per entity."
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.organization"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomAttributeEnum",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=255)),
                ("value", models.SlugField(max_length=255)),
                ("color_code", models.CharField(blank=True, max_length=6)),
                (
                    "attribute",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.customattribute"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomAttributeValue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("object_id", models.UUIDField()),
                ("value_date", models.DateField(blank=True, null=True)),
                (
                    "attribute",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.customattribute"),
                ),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "value_enum",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.customattributeenum",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="customattribute",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_type__in", ["enum", "date"])), name="core_CustomAttribute_data_type_DataType"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customattributeenum",
            unique_together={("attribute", "value")},
        ),
        migrations.AddIndex(
            model_name="customattributevalue",
            index=models.Index(fields=["content_type", "object_id"], name="core_custom_content_70d2c6_idx"),
        ),
    ]
