# Generated by Django 5.2.7 on 2025-10-27 18:49

from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group
from django.db import migrations
from guardian.shortcuts import assign_perm


# Build permissions now instead of in post_migrate signal. Allowing access to
# permissions created in the depedent migration.
#
# https://webinative.com/blog/django-permission-not-found-error/
def ensure_permissions_exist(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def backfill_provider_create_patient_perms(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")

    for org in Organization.objects.all():
        roles = org.role_set.exclude(name="patient")
        for role in roles:
            group = Group.objects.get(id=role.group.id)
            assign_perm("create_patient", group, org)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_customattribute_customattributeenum_and_more"),
    ]

    operations = [
        migrations.RunPython(ensure_permissions_exist, migrations.RunPython.noop),
        migrations.RunPython(backfill_provider_create_patient_perms, migrations.RunPython.noop),
    ]
