# Generated by Django 5.2.7 on 2025-10-27 16:38
from django.contrib.auth import get_user_model
from django.contrib.auth.management import create_permissions
from django.db import migrations
from guardian.shortcuts import assign_perm


# Build permissions now instead of in post_migrate signal. Allowing access to
# permissions created in the depedent migration.
#
# https://webinative.com/blog/django-permission-not-found-error/
def ensure_permissions_exist(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def backfill_patient_task_perms(apps, schema_editor):
    Task = apps.get_model("core", "Task")
    User = get_user_model()  # noqa: N806

    tasks = Task.objects.all()
    for task in tasks:
        if task.patient.user:
            user = User.objects.get(id=task.patient.user.id)
            if user:
                assign_perm("view_task", user, task)
                assign_perm("complete_task", user, task)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_backfill_provider_create_patient_perms"),
    ]

    operations = [
        migrations.RunPython(ensure_permissions_exist, migrations.RunPython.noop),
        migrations.RunPython(backfill_patient_task_perms, migrations.RunPython.noop),
    ]
