# Generated by Django 5.2.7 on 2025-10-28 14:37

import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_backfill_patient_task_perms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="The name of the form", max_length=255)),
                ("schema", models.JSONField(default=dict, help_text="The surveyjs JSON schema of the form")),
                (
                    "organization",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.organization"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("organization", "name"), name="unique_form_name_per_organization")
                ],
            },
        ),
    ]
