# Generated by Django 5.2.7 on 2025-10-27 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_backfill_patient_task_perms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    ("create_patient", "Can create a new patient in this organization."),
                    ("create_encounter", "Can create a new patient encounter in this organization."),
                    ("create_invitation", "Can create a invitation on behalf of this organization."),
                )
            },
        ),
    ]
