# Generated by Django 5.2.7 on 2025-10-28 14:38

import uuid

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_form"),
        ("pghistory", "0007_auto_20250421_0444"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ("name", models.CharField(help_text="The name of the form", max_length=255)),
                ("schema", models.JSONField(default=dict, help_text="The surveyjs JSON schema of the form")),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="form",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_formevent" ("created_at", "id", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "schema", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", NEW."organization_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."schema", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="9f76feffd4bca8714f73756d220397f4715a4696",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_3e5b3",
                    table="core_form",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="form",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_formevent" ("created_at", "id", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "schema", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", NEW."organization_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."schema", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="e709b6dd902aea75118999b35086e85d1e8a81e0",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_10ed0",
                    table="core_form",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="formevent",
            name="organization",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="formevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="formevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="core.form",
            ),
        ),
    ]
