# Generated by Django 5.2.7 on 2025-10-28 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_formevent_form_insert_insert_form_update_update_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "permissions": (
                    ("assign_task", "Can assign a task to this patient"),
                    ("create_document", "Can create a new document for this patient."),
                )
            },
        ),
    ]
