# Generated by Django 5.2.7 on 2025-10-28 15:43

import django.db.migrations.operations.special
import django_enum.fields
from django.conf import settings
from django.db import migrations
from django.db import models


def cleanup_provenance_source_type(apps, schema_editor):
    Provenance = apps.get_model("core", "Provenance")
    # if there's a document, source_type should be document
    for p in Provenance.objects.filter(document__isnull=False).exclude(source_type="document"):
        p.source_type = "document"
        p.save()
    # if source_type isn't document or text, set source_type to unknown
    for p in Provenance.objects.exclude(source_type__in=["document", "text"]):
        p.source_type = "unknown"
        p.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_alter_patient_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=cleanup_provenance_source_type,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="provenance",
            name="source_type",
            field=django_enum.fields.EnumCharField(
                choices=[("document", "Document upload"), ("text", "Text"), ("unknown", "Unknown")],
                default="unknown",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="provenance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("document__isnull", False), ("source_type", "document")),
                    models.Q(("source_type", "document"), _negated=True),
                    _connector="OR",
                ),
                name="document_required_for_document_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="provenance",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_type__in", ["document", "text", "unknown"])),
                name="core_Provenance_source_type_SourceType",
            ),
        ),
    ]
