# Generated by Django 5.2.7 on 2025-10-28 16:35

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_cleanup_provenance_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="form_version",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific version of the form this task uses",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="core.formevent",
            ),
        ),
    ]
