# Generated by Django 5.2.7 on 2025-10-28 20:51

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_backfill_invitation_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customattribute",
            name="data_type",
            field=django_enum.fields.EnumCharField(choices=[("enum", "Select"), ("date", "Date")], max_length=4),
        ),
    ]
