# Generated by Django 5.2.7 on 2025-10-28 21:37

from django.contrib.auth import get_user_model
from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group
from django.db import migrations
from guardian.shortcuts import assign_perm


# Build permissions now instead of in post_migrate signal. Allowing access to
# permissions created in the depedent migration.
#
# https://webinative.com/blog/django-permission-not-found-error/
def ensure_permissions_exist(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def backfill_document_perms(apps, schema_editor):
    Document = apps.get_model("core", "Document")
    Patient = apps.get_model("core", "Patient")
    User = get_user_model()  # noqa: N806

    for doc in Document.objects.all():
        if doc.patient.organization:
            roles = doc.patient.organization.role_set.exclude(name="patient")
            for role in roles:
                group = Group.objects.get(id=role.group.id)
                assign_perm("change_document", group, doc)
                assign_perm("view_document", group, doc)
                assign_perm("delete_document", group, doc)
        if doc.patient.user:
            user = User.objects.get(id=doc.patient.user.id)
            assign_perm("view_document", user, doc)
            assign_perm("change_document", user, doc)
            assign_perm("delete_document", user, doc)

    for patient in Patient.objects.all():
        if patient.user:
            user = User.objects.get(id=patient.user.id)
            assign_perm("create_document", user, patient)
        if patient.organization:
            roles = patient.organization.role_set.exclude(name="patient")
            for role in roles:
                group = Group.objects.get(id=role.group.id)
                assign_perm("create_document", group, patient)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_alter_customattribute_data_type"),
    ]

    operations = [
        migrations.RunPython(ensure_permissions_exist, migrations.RunPython.noop),
        migrations.RunPython(backfill_document_perms, migrations.RunPython.noop),
    ]
