# Generated by Django 5.2.7 on 2025-10-28 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0057_backfill_document_perms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patient",
            options={
                "permissions": (
                    ("create_task", "Can create a task for this patient"),
                    ("create_document", "Can create a new document for this patient."),
                )
            },
        ),
    ]
