# Generated by Django 5.2.7 on 2025-10-28 17:46
import logging

from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group
from django.db import migrations
from guardian.shortcuts import assign_perm

logger = logging.getLogger(__name__)


# Build permissions now instead of in post_migrate signal. Allowing access to
# permissions created in the depedent migration.
#
# https://webinative.com/blog/django-permission-not-found-error/
def ensure_permissions_exist(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def update_permission_assignments(apps, schema_editor):
    # Backfill the new "create_task" perm to all providers from same organization
    Patient = apps.get_model("core", "Patient")
    patients = Patient.objects.all()
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    for patient in patients:
        if not patient.organization:
            continue

        roles = patient.organization.role_set.exclude(name="patient")
        for role in roles:
            group = Group.objects.get(id=role.group.id)
            assign_perm("create_task", group, patient)

    # Clean up the old "assign_task" perm and delete it from auth table
    try:
        patient_content_type = ContentType.objects.get_for_model(Patient)
        old_user_object_permission = apps.get_model("guardian", "UserObjectPermission")

        old_group_object_permission = apps.get_model("guardian", "GroupObjectPermission")
        old_perm = Permission.objects.get(content_type=patient_content_type, codename="assign_task")
        old_user_object_permission.objects.filter(permission=old_perm, content_type=patient_content_type).delete()
        old_group_object_permission.objects.filter(permission=old_perm, content_type=patient_content_type).delete()
        old_perm.delete()
    except Permission.DoesNotExist:
        logger.info("  Warning: Old permission not found. No cleanup needed.")
    except ContentType.DoesNotExist:
        logger.info("  Warning: ContentType for not found. Cleanup failed.")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_alter_patient_options"),
        ("guardian", "0002_generic_permissions_index"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(ensure_permissions_exist, migrations.RunPython.noop),
        migrations.RunPython(update_permission_assignments, migrations.RunPython.noop),
    ]
