# Generated by Django 5.2.7 on 2025-10-28 16:18

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_update_patient_permissions_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                help_text="Only populated when `Entity.type` == PATIENT",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.patient",
            ),
        ),
    ]
