# Generated by Django 5.2.7 on 2025-10-28 17:16

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_backfill_entity_patient"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entity",
            name="unique_patient_id_in_metadata",
        ),
        migrations.AddConstraint(
            model_name="entity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("patient__isnull", False), ("type", "Patient")),
                fields=("patient",),
                name="unique_patient_fk",
            ),
        ),
    ]
