# Generated by Django 5.2.7 on 2025-10-29 19:51

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_remove_entity_unique_patient_id_in_metadata_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListViewPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "scope",
                    models.CharField(
                        choices=[("user", "User"), ("organization", "Organization")], default="user", max_length=20
                    ),
                ),
                (
                    "list_type",
                    models.CharField(
                        choices=[("encounter_list", "Encounter List"), ("patient_list", "Patient List")], max_length=50
                    ),
                ),
                (
                    "visible_columns",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        help_text="Ordered list of visible column names",
                        size=None,
                    ),
                ),
                (
                    "default_sort",
                    models.CharField(blank=True, help_text="Default sort field (e.g., '-updated_at')", max_length=100),
                ),
                ("saved_filters", models.JSONField(blank=True, default=dict, help_text="Saved filter presets")),
                ("items_per_page", models.PositiveIntegerField(default=25, help_text="Number of items per page")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_view_preferences",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_view_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "user")),
                        fields=("user", "organization", "list_type"),
                        name="unique_user_list_view_preference",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("scope", "organization"), ("user__isnull", True)),
                        fields=("organization", "list_type"),
                        name="unique_org_list_view_preference",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("scope", "user"), ("user__isnull", False)),
                            models.Q(("scope", "organization"), ("user__isnull", True)),
                            _connector="OR",
                        ),
                        name="scope_user_consistency",
                    ),
                ],
            },
        ),
    ]
