# Generated by Django 5.2.7 on 2025-10-31 15:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_listviewpreference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encounter",
            name="patient_status",
        ),
    ]
