# Generated by Django 5.2.7 on 2025-10-31 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_remove_patient_status_from_encounter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="patient_statuses",
        ),
    ]
