# Generated by Django 5.2.7 on 2025-10-31 18:29

import uuid

import django.db.models.deletion
import django_enum.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_remove_patient_statuses_from_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[("draft", "Draft"), ("completed", "Completed")],
                        help_text="current state of submission",
                        max_length=9,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("submitted_at", models.DateTimeField(null=True)),
                (
                    "form",
                    models.ForeignKey(
                        help_text="The original form this submission is for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.form",
                    ),
                ),
                (
                    "form_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The specific version of the form this submission uses",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.formevent",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="The patient this form submission is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.patient",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        help_text="The specific task this submission is for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.task",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["draft", "completed"])),
                        name="core_Submission_status_SubmissionStatus",
                    )
                ],
            },
        ),
    ]
