# Generated by Django 5.2.7 on 2025-11-03 19:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_submission"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Submission",
            new_name="FormSubmission",
        ),
        migrations.RemoveConstraint(
            model_name="formsubmission",
            name="core_Submission_status_SubmissionStatus",
        ),
        migrations.AddConstraint(
            model_name="formsubmission",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "completed"])),
                name="core_FormSubmission_status_FormSubmissionStatus",
            ),
        ),
    ]
