# Generated by Django 5.2.7 on 2025-11-03 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_rename_submission_formsubmission_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    ("create_patient", "Can create a new patient in this organization."),
                    ("create_encounter", "Can create a new patient encounter in this organization."),
                    ("create_invitation", "Can create a invitation on behalf of this organization."),
                    ("create_form", "Can create a new form in this organization."),
                )
            },
        ),
    ]
