# Generated by Django 5.2.7 on 2025-11-03 23:45
from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group
from django.db import migrations
from guardian.shortcuts import assign_perm


# Build permissions now instead of in post_migrate signal. Allowing access to
# permissions created in the dependent migration.
#
# https://webinative.com/blog/django-permission-not-found-error/
def ensure_permissions_exist(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def backfill_form_permissions(apps, schema_editor):
    """For existing forms, give necessary access to the org roles.

    This should match the object-level permissions given in form service.
    """
    Form = apps.get_model("core", "Form")

    for form in Form.objects.all():
        # For all roles, except patient.
        roles = form.organization.role_set.exclude(name="patient")
        for role in roles:
            # give the group permissions on the specific form.
            group = Group.objects.get(id=role.group.id)
            match role.name:
                case "admin":
                    assign_perm("change_form", group, form)
                    assign_perm("view_form", group, form)
                    assign_perm("delete_form", group, form)
                case "owner":
                    assign_perm("change_form", group, form)
                    assign_perm("view_form", group, form)
                    assign_perm("delete_form", group, form)
                case "staff":
                    assign_perm("view_form", group, form)


def backfill_organization_create_form_permission(apps, schema_editor):
    """For existing organization roles, add the "create_form" permission that was recently added.

    This should match the permissions granted per role in organization service.
    """
    Organization = apps.get_model("core", "Organization")

    # For each existing org.
    for organization in Organization.objects.all():
        # For their owner and admin roles only.
        roles = organization.role_set.exclude(name="patient").exclude(name="staff")
        for role in roles:
            # Add the 'create_form' permission to each.
            group = Group.objects.get(id=role.group.id)
            assign_perm("create_form", group, organization)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_alter_organization_options"),
    ]

    operations = [
        migrations.RunPython(ensure_permissions_exist, migrations.RunPython.noop),
        migrations.RunPython(backfill_form_permissions, migrations.RunPython.noop),
        migrations.RunPython(backfill_organization_create_form_permission, migrations.RunPython.noop),
    ]
