# Generated by Django 5.2.7 on 2025-11-04 18:09

import uuid

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import private_storage.fields
import private_storage.storage.files
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_backfill_form_perms"),
        ("pghistory", "0007_auto_20250421_0444"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "file",
                    private_storage.fields.PrivateFileField(
                        storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to="documents/"
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Immunization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImmunizationEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="encounter",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.encounter"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_documentevent" ("content_type", "created_at", "encounter_id", "file", "id", "original_filename", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "updated_at") VALUES (NEW."content_type", NEW."created_at", NEW."encounter_id", NEW."file", NEW."id", NEW."original_filename", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."size", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="bca7fe5db38bd215e714594c3ffedcb0d10cf2ac",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_b5daa",
                    table="core_document",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_documentevent" ("content_type", "created_at", "encounter_id", "file", "id", "original_filename", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "updated_at") VALUES (NEW."content_type", NEW."created_at", NEW."encounter_id", NEW."file", NEW."id", NEW."original_filename", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."size", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="02ebc4d978f98679a8596bece96f465bc534beb5",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_931a9",
                    table="core_document",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="documentevent",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.encounter",
            ),
        ),
        migrations.AddField(
            model_name="documentevent",
            name="patient",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.patient",
            ),
        ),
        migrations.AddField(
            model_name="documentevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="documentevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="core.document",
            ),
        ),
        migrations.AddField(
            model_name="immunization",
            name="encounter",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.encounter"
            ),
        ),
        migrations.AddField(
            model_name="immunization",
            name="patient",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.patient"),
        ),
        migrations.AddField(
            model_name="immunizationevent",
            name="encounter",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.encounter",
            ),
        ),
        migrations.AddField(
            model_name="immunizationevent",
            name="patient",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="core.patient",
            ),
        ),
        migrations.AddField(
            model_name="immunizationevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="immunizationevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="core.immunization",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="immunization",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_immunizationevent" ("created_at", "date", "encounter_id", "id", "name", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."date", NEW."encounter_id", NEW."id", NEW."name", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="1a48ab93dd8dd8a1cbc9e8c22cb8b3f707a56f44",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_0a1a6",
                    table="core_immunization",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="immunization",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_immunizationevent" ("created_at", "date", "encounter_id", "id", "name", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."date", NEW."encounter_id", NEW."id", NEW."name", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="32009c3102071de66c40be126b0a88603c0438b5",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_ccc49",
                    table="core_immunization",
                    when="AFTER",
                ),
            ),
        ),
    ]
