# Generated by Django 5.2.7 on 2025-11-05 19:51

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_practitioner_practitionerevent_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="document",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="document",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="immunization",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="immunization",
            name="update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="practitioner",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="practitioner",
            name="update_update",
        ),
        migrations.AddField(
            model_name="document",
            name="unattested",
            field=models.BooleanField(
                default=False,
                help_text="True if this record was generated by an AI agent and has not been confirmed by a human.",
            ),
        ),
        migrations.AddField(
            model_name="documentevent",
            name="unattested",
            field=models.BooleanField(
                default=False,
                help_text="True if this record was generated by an AI agent and has not been confirmed by a human.",
            ),
        ),
        migrations.AddField(
            model_name="immunization",
            name="unattested",
            field=models.BooleanField(
                default=False,
                help_text="True if this record was generated by an AI agent and has not been confirmed by a human.",
            ),
        ),
        migrations.AddField(
            model_name="immunizationevent",
            name="unattested",
            field=models.BooleanField(
                default=False,
                help_text="True if this record was generated by an AI agent and has not been confirmed by a human.",
            ),
        ),
        migrations.AddField(
            model_name="practitioner",
            name="unattested",
            field=models.BooleanField(
                default=False,
                help_text="True if this record was generated by an AI agent and has not been confirmed by a human.",
            ),
        ),
        migrations.AddField(
            model_name="practitionerevent",
            name="unattested",
            field=models.BooleanField(
                default=False,
                help_text="True if this record was generated by an AI agent and has not been confirmed by a human.",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_documentevent" ("content_type", "created_at", "encounter_id", "file", "id", "original_filename", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "unattested", "updated_at") VALUES (NEW."content_type", NEW."created_at", NEW."encounter_id", NEW."file", NEW."id", NEW."original_filename", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."size", NEW."unattested", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="f1506ffb3212ff883cf1727640552e2a09641001",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_b5daa",
                    table="core_document",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_documentevent" ("content_type", "created_at", "encounter_id", "file", "id", "original_filename", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "unattested", "updated_at") VALUES (NEW."content_type", NEW."created_at", NEW."encounter_id", NEW."file", NEW."id", NEW."original_filename", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."size", NEW."unattested", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="0a93520ec41d6e545bec927ee87393ee8d59fc9a",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_931a9",
                    table="core_document",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="immunization",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_immunizationevent" ("created_at", "date", "encounter_id", "id", "name", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "unattested", "updated_at") VALUES (NEW."created_at", NEW."date", NEW."encounter_id", NEW."id", NEW."name", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."unattested", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="0ba34af3f2647fd8590a0f6524d9e078e860e3ab",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_0a1a6",
                    table="core_immunization",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="immunization",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_immunizationevent" ("created_at", "date", "encounter_id", "id", "name", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "unattested", "updated_at") VALUES (NEW."created_at", NEW."date", NEW."encounter_id", NEW."id", NEW."name", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."unattested", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="b31b827af313cdbf23ab827fc892370ab77a864e",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_ccc49",
                    table="core_immunization",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="practitioner",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_practitionerevent" ("created_at", "encounter_id", "id", "name", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "unattested", "updated_at") VALUES (NEW."created_at", NEW."encounter_id", NEW."id", NEW."name", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."unattested", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="6eb606a56c39de1e012467ac64d476ef3ef75c6f",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_eb993",
                    table="core_practitioner",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="practitioner",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_practitionerevent" ("created_at", "encounter_id", "id", "name", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "unattested", "updated_at") VALUES (NEW."created_at", NEW."encounter_id", NEW."id", NEW."name", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."unattested", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="a7090bf002105af78febe6fc22f9c1d871255264",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_79181",
                    table="core_practitioner",
                    when="AFTER",
                ),
            ),
        ),
    ]
