# Generated by Django 5.2.8 on 2025-11-06 16:58

import django_enum.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_remove_document_insert_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="document",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="document",
            name="update_update",
        ),
        migrations.AddField(
            model_name="document",
            name="category",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("lab_results", "Lab Results"),
                    ("health_visits", "Health Visits"),
                    ("hospital_visits", "Hospital Visits"),
                    ("immunizations", "Immunizations"),
                    ("prescriptions", "Prescriptions"),
                    ("my_notes", "My Notes"),
                    ("family_history", "Family History"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentevent",
            name="category",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("lab_results", "Lab Results"),
                    ("health_visits", "Health Visits"),
                    ("hospital_visits", "Hospital Visits"),
                    ("immunizations", "Immunizations"),
                    ("prescriptions", "Prescriptions"),
                    ("my_notes", "My Notes"),
                    ("family_history", "Family History"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="documentevent",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_documentevent" ("category", "content_type", "created_at", "date", "encounter_id", "file", "id", "original_filename", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "unattested", "updated_at") VALUES (NEW."category", NEW."content_type", NEW."created_at", NEW."date", NEW."encounter_id", NEW."file", NEW."id", NEW."original_filename", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."size", NEW."unattested", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="1e4dae4b9dbcefc0a1480dd5af09fe77cc93409b",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_b5daa",
                    table="core_document",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="document",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_documentevent" ("category", "content_type", "created_at", "date", "encounter_id", "file", "id", "original_filename", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "unattested", "updated_at") VALUES (NEW."category", NEW."content_type", NEW."created_at", NEW."date", NEW."encounter_id", NEW."file", NEW."id", NEW."original_filename", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."size", NEW."unattested", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="8678866c5494224162e2690ef4c7b98b75fe36a9",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_931a9",
                    table="core_document",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "category__in",
                        [
                            "lab_results",
                            "health_visits",
                            "hospital_visits",
                            "immunizations",
                            "prescriptions",
                            "my_notes",
                            "family_history",
                            "other",
                        ],
                    )
                ),
                name="core_Document_category_DocumentCategory",
            ),
        ),
    ]
