# Generated by Django 5.2.8 on 2025-11-06 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0073_document_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formsubmission",
            name="form",
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who filled out the submission",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
