# Generated by Django 5.2.8 on 2025-11-06 17:51

from django.db import migrations


def backfill_completed_form_submissions(apps, schema_editor):
    FormSubmission = apps.get_model("core", "FormSubmission")

    submissions = FormSubmission.objects.filter(status="completed", patient__user__isnull=False)

    for submission in submissions.iterator():
        submission.submitted_by_id = submission.patient.user_id
        submission.save(update_fields=["submitted_by_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_remove_formsubmission_form_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_completed_form_submissions, migrations.RunPython.noop),
    ]
