# Generated by Django 5.2.8 on 2025-11-07 20:36

import uuid

import django.db.models.deletion
import django_enum.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models

import sandwich.core.mixins.versioning


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0076_install_postgres_checkpoint_saver"),
        ("pghistory", "0007_auto_20250421_0444"),
    ]

    operations = [
        migrations.CreateModel(
            name="Condition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "unattested",
                    models.BooleanField(
                        default=False,
                        help_text="True if this record was generated by an AI agent and has not been confirmed by a human.",  # noqa: E501
                    ),
                ),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("active", "Active"),
                            ("recurrence", "Recurrence"),
                            ("relapse", "Relapse"),
                            ("inactive", "Inactive"),
                            ("remission", "Remission"),
                            ("resolved", "Resolved"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("onset", models.DateField(blank=True, null=True)),
                ("abatement", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.encounter"
                    ),
                ),
                ("patient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.patient")),
            ],
            options={
                "abstract": False,
            },
            bases=(sandwich.core.mixins.versioning.VersionMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ConditionEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                (
                    "unattested",
                    models.BooleanField(
                        default=False,
                        help_text="True if this record was generated by an AI agent and has not been confirmed by a human.",  # noqa: E501
                    ),
                ),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("active", "Active"),
                            ("recurrence", "Recurrence"),
                            ("relapse", "Relapse"),
                            ("inactive", "Inactive"),
                            ("remission", "Remission"),
                            ("resolved", "Resolved"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("onset", models.DateField(blank=True, null=True)),
                ("abatement", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="core.encounter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="core.patient",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="core.condition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="condition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["active", "recurrence", "relapse", "inactive", "remission", "resolved", "unknown"])
                ),
                name="core_Condition_status_ConditionStatus",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="condition",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_conditionevent" ("abatement", "created_at", "encounter_id", "id", "name", "onset", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "unattested", "updated_at") VALUES (NEW."abatement", NEW."created_at", NEW."encounter_id", NEW."id", NEW."name", NEW."onset", NEW."patient_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."unattested", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="547b232f3f1cc5a19e72bba57736be6e1b2849ef",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_ad432",
                    table="core_condition",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="condition",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_conditionevent" ("abatement", "created_at", "encounter_id", "id", "name", "onset", "patient_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "unattested", "updated_at") VALUES (NEW."abatement", NEW."created_at", NEW."encounter_id", NEW."id", NEW."name", NEW."onset", NEW."patient_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."unattested", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="a98f329ec508c0f6e3eda41f54a2c01450fa846f",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_4371c",
                    table="core_condition",
                    when="AFTER",
                ),
            ),
        ),
    ]
