# Generated by Django 5.2.8 on 2025-11-08 01:38

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_condition_conditionevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="task",
            field=models.OneToOneField(
                blank=True,
                help_text="The specific task this submission is for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_submission",
                to="core.task",
            ),
        ),
    ]
