# Generated by Django 5.2.8 on 2025-11-10 18:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_alter_formsubmission_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckpointBlobs",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "thread_id",
                        "checkpoint_ns",
                        "channel",
                        "version",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("thread_id", models.TextField()),
                ("checkpoint_ns", models.TextField()),
                ("channel", models.TextField()),
                ("version", models.TextField()),
                ("type", models.TextField()),
                ("blob", models.BinaryField(blank=True, null=True)),
            ],
            options={
                "db_table": "checkpoint_blobs",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CheckpointMigrations",
            fields=[
                ("v", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "checkpoint_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Checkpoints",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "thread_id",
                        "checkpoint_ns",
                        "checkpoint_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("thread_id", models.TextField()),
                ("checkpoint_ns", models.TextField()),
                ("checkpoint_id", models.TextField()),
                ("parent_checkpoint_id", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("checkpoint", models.JSONField()),
                ("metadata", models.JSONField()),
            ],
            options={
                "db_table": "checkpoints",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CheckpointWrites",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "thread_id",
                        "checkpoint_ns",
                        "checkpoint_id",
                        "task_id",
                        "idx",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("thread_id", models.TextField()),
                ("checkpoint_ns", models.TextField()),
                ("checkpoint_id", models.TextField()),
                ("task_id", models.TextField()),
                ("idx", models.IntegerField()),
                ("channel", models.TextField()),
                ("type", models.TextField(blank=True, null=True)),
                ("blob", models.BinaryField()),
                ("task_path", models.TextField()),
            ],
            options={
                "db_table": "checkpoint_writes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "prefix", "key", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("prefix", models.TextField()),
                ("key", models.TextField()),
                ("value", models.JSONField()),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("ttl_minutes", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "store",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StoreMigrations",
            fields=[
                ("v", models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "store_migrations",
                "managed": False,
            },
        ),
    ]
