# Generated by Django 5.2.8 on 2025-11-10 20:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_checkpointblobs_checkpointmigrations_checkpoints_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(fields=["organization", "status"], name="core_encounter_org_status_idx"),
        ),
    ]
