# Generated by Django 5.2.8 on 2025-11-13 20:21

import pgtrigger.compiler
import pgtrigger.migrations
import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_encounter_core_encounter_org_status_idx"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="form",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="form",
            name="update_update",
        ),
        migrations.AddField(
            model_name="form",
            name="reference_file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="form_reference_files/",
            ),
        ),
        migrations.AddField(
            model_name="formevent",
            name="reference_file",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="form_reference_files/",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="form",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_formevent" ("created_at", "id", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_file", "schema", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", NEW."organization_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference_file", NEW."schema", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="853cf5291d26cc7493b35217e276c0e581ec6843",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_3e5b3",
                    table="core_form",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="form",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_formevent" ("created_at", "id", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_file", "schema", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", NEW."organization_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference_file", NEW."schema", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="e34a08807eee0ad850d606402b00142b53d8dbde",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_10ed0",
                    table="core_form",
                    when="AFTER",
                ),
            ),
        ),
    ]
