# Generated by Django 5.2.8 on 2025-11-14 16:37

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0081_remove_form_insert_insert_remove_form_update_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customattributevalue",
            name="attribute",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.customattribute"),
        ),
    ]
