# Generated by Django 5.2.8 on 2025-11-18 17:00

import uuid

import django.db.models.deletion
import django_enum.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_custom_attribute_cascade_delete"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    ("create_patient", "Can create a new patient in this organization."),
                    ("create_encounter", "Can create a new patient encounter in this organization."),
                    ("create_invitation", "Can create a invitation on behalf of this organization."),
                    ("create_form", "Can create a new form in this organization."),
                    ("create_summarytemplate", "Can create summary templates in this organization."),
                )
            },
        ),
        migrations.CreateModel(
            name="SummaryTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Display name for the template", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Optional description of the template's purpose and usage"),
                ),
                (
                    "text",
                    models.TextField(help_text="Template content using Django template syntax with {% ai %} tags"),
                ),
                (
                    "form",
                    models.ForeignKey(
                        help_text="Form that this template is associated with",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.form",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization that owns this template",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Summary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(help_text="Title of the summary (usually from template name)", max_length=255),
                ),
                ("body", models.TextField(blank=True, help_text="Generated markdown/HTML content")),
                (
                    "status",
                    django_enum.fields.EnumCharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current generation status",
                        max_length=10,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional encounter context for this summary",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.encounter",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization for access control",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient this summary is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.patient",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="Form submission being summarized",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.formsubmission",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template used to generate this summary",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.summarytemplate",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Summaries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="summarytemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_template_name_per_organization"
            ),
        ),
        migrations.AddConstraint(
            model_name="summary",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "processing", "succeeded", "failed"])),
                name="core_Summary_status_SummaryStatus",
            ),
        ),
    ]
