# Generated by Django 5.2.8 on 2025-11-19 21:37

from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group
from django.db import migrations
from guardian.shortcuts import assign_perm


# Build permissions now instead of in post_migrate signal. Allowing access to
# permissions created in the dependent migration.
#
# https://webinative.com/blog/django-permission-not-found-error/
def ensure_permissions_exist(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def backfill_summarytemplate_permissions(apps, schema_editor):
    """Backfill permissions for existing Organizations."""
    Organization = apps.get_model("core", "Organization")
    Role = apps.get_model("core", "Role")

    # Assign org-level permissions to existing organizations
    for org in Organization.objects.all():
        try:
            owner_role = Role.objects.get(organization=org, name="owner")
            admin_role = Role.objects.get(organization=org, name="admin")
        except Role.DoesNotExist:
            continue

        owner_group = Group.objects.get(id=owner_role.group_id)
        admin_group = Group.objects.get(id=admin_role.group_id)

        assign_perm("create_summarytemplate", owner_group, org)
        assign_perm("delete_summarytemplate", owner_group, org)

        assign_perm("create_summarytemplate", admin_group, org)
        assign_perm("delete_summarytemplate", admin_group, org)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_alter_organization_options_summarytemplate_summary_and_more"),
        ("contenttypes", "__latest__"),
        ("auth", "__latest__"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "permissions": (
                    ("create_patient", "Can create a new patient in this organization."),
                    ("create_encounter", "Can create a new patient encounter in this organization."),
                    ("create_invitation", "Can create a invitation on behalf of this organization."),
                    ("create_form", "Can create a new form in this organization."),
                    ("create_summarytemplate", "Can create summary templates in this organization."),
                    ("delete_summarytemplate", "Can delete summary templates in this organization."),
                )
            },
        ),
        migrations.RunPython(ensure_permissions_exist, migrations.RunPython.noop),
        migrations.RunPython(backfill_summarytemplate_permissions, migrations.RunPython.noop),
    ]
