# Generated by Django 5.2.8 on 2025-11-22 01:17

import django_enum.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_add_summarytemplate_permissions"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="form",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="form",
            name="update_update",
        ),
        migrations.AddField(
            model_name="form",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("active", "Active"),
                    ("generating", "Generating"),
                    ("failed", "Failed"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="formevent",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("active", "Active"),
                    ("generating", "Generating"),
                    ("failed", "Failed"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="form",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "core_formevent" ("created_at", "id", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_file", "schema", "status", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", NEW."organization_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference_file", NEW."schema", NEW."status", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="af92f032bb6512e79594179c9cd34fd9035a8465",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_3e5b3",
                    table="core_form",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="form",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "core_formevent" ("created_at", "id", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_file", "schema", "status", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", NEW."organization_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference_file", NEW."schema", NEW."status", NEW."updated_at"); RETURN NULL;',  # noqa: E501
                    hash="ac59456f2ec420d81710af9ac68cad5e6a612818",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_10ed0",
                    table="core_form",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "generating", "failed"])),
                name="core_Form_status_FormStatus",
            ),
        ),
    ]
