# Generated by Django 5.2.8 on 2025-11-24 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_remove_form_insert_insert_remove_form_update_update_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customattributeenum",
            options={"ordering": ["label"]},
        ),
    ]
