# Generated by Django 5.2.8 on 2025-11-26 19:48

import django_enum.fields
from django.db import migrations
from django.db import models


def convert_dismissed_to_failed(apps, schema_editor):
    """Convert any DISMISSED forms back to FAILED when rolling back."""
    Form = apps.get_model("core", "Form")
    Form.objects.filter(status="dismissed").update(status="failed")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_attachment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="form",
            name="core_Form_status_FormStatus",
        ),
        migrations.AlterField(
            model_name="form",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("active", "Active"),
                    ("generating", "Generating"),
                    ("failed", "Failed"),
                    ("dismissed", "Dismissed"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="formevent",
            name="status",
            field=django_enum.fields.EnumCharField(
                choices=[
                    ("active", "Active"),
                    ("generating", "Generating"),
                    ("failed", "Failed"),
                    ("dismissed", "Dismissed"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        # When rolling back, convert dismissed forms to failed before adding old constraint
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=convert_dismissed_to_failed,
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "generating", "failed", "dismissed"])),
                name="core_Form_status_FormStatus",
            ),
        ),
    ]
