# Generated by Django 5.2.8 on 2025-11-27 00:13

import uuid

import django.db.models.deletion
import django_enum.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_add_dismissed_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalSummary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("body", models.TextField(blank=True, help_text="Generated HTML content")),
                (
                    "summary_type",
                    django_enum.fields.EnumCharField(
                        choices=[("health_summary", "Health Summary")],
                        default="health_summary",
                        help_text="The type of personal summary generated",
                        max_length=14,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient this summary is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PersonalSummaries",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("summary_type__in", ["health_summary"])),
                        name="core_PersonalSummary_summary_type_PersonalSummaryType",
                    )
                ],
            },
        ),
    ]
