# Generated by Django 5.2.8 on 2025-11-27 17:56

from django.db import migrations
from django.db import models

import sandwich.core.validators.surveyjs_form_validator


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_personalsummary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The surveyjs JSON schema of the form",
                validators=[sandwich.core.validators.surveyjs_form_validator.validate_survey_json],
            ),
        ),
        migrations.AlterField(
            model_name="formevent",
            name="schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The surveyjs JSON schema of the form",
                validators=[sandwich.core.validators.surveyjs_form_validator.validate_survey_json],
            ),
        ),
    ]
