# Generated by Django 5.2.8 on 2025-11-27 20:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0090_alter_form_schema_alter_formevent_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="verified",
            field=models.BooleanField(
                default=False, help_text="Specifies an organization is authorized to interact with patients"
            ),
        ),
    ]
