# Generated by Django 5.2.6 on 2025-09-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0002_patient_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
