#!/bin/bash
set -euo pipefail

# TODO-NG: why do we need to re-run this on startup? shouldn't it be a build step?
python /app/manage.py collectstatic --noinput

python /app/manage.py migrate --noinput

exec ddtrace-run granian config.asgi:application --interface asginl --host 0.0.0.0 --port 3000
