import pghistory
from django.db import models
from django_enum import EnumField
from private_storage.fields import PrivateFileField

from sandwich.core.mixins.versioning import VersionMixin
from sandwich.core.models.abstract import BaseModel
from sandwich.core.models.organization import Organization
from sandwich.core.validators.surveyjs_form_validator import validate_survey_json


class FormManager(models.Manager["Form"]):
    def create(self, **kwargs) -> "Form":
        from sandwich.core.service.form_service import assign_default_form_permissions  # noqa: PLC0415

        form = super().create(**kwargs)
        assign_default_form_permissions(form)
        return form


class FormStatus(models.TextChoices):
    ACTIVE = "active"
    # Form is being generated by AI
    GENERATING = "generating"
    # Form failed AI generation
    FAILED = "failed"
    # Failed form dismissed by user
    DISMISSED = "dismissed"


@pghistory.track()
class Form(VersionMixin, BaseModel):
    """A form that can be rendered using the surveyjs library."""

    name = models.CharField(max_length=255, help_text="The name of the form")
    schema = models.JSONField(
        default=dict, help_text="The surveyjs JSON schema of the form", blank=True, validators=[validate_survey_json]
    )
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    reference_file = PrivateFileField(upload_to="form_reference_files/", null=True, blank=True)
    status: models.Field[FormStatus, FormStatus] = EnumField(FormStatus, default=FormStatus.ACTIVE)

    objects = FormManager()

    def __str__(self) -> str:
        return self.name

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["organization", "name"], name="unique_form_name_per_organization")
        ]

    def current_version(self) -> int:
        return self.get_total_versions()

    @property
    def is_generating(self) -> bool:
        return self.status == FormStatus.GENERATING
