from django.db import models
from django.utils.translation import gettext_lazy as _
from django_enum import EnumField

from sandwich.core.models.abstract import BaseModel
from sandwich.core.models.patient import Patient


class PersonalSummaryType(models.TextChoices):
    # Healthy Summary generated by AI from chat interface.
    HEALTH_SUMMARY = "health_summary", _("Health Summary")


class PersonalSummaryManager(models.Manager["PersonalSummary"]):
    def get_most_recent_summary(
        self, patient: Patient, summary_type: PersonalSummaryType | None = None
    ) -> "PersonalSummary | None":
        """Return most recent health summary.

        This is the Health Summary generated by AI, triggered by the patient via the chat interface.
        """
        if not summary_type:
            summary_type = PersonalSummaryType.HEALTH_SUMMARY
        return (
            self.filter(
                patient=patient,
                summary_type=summary_type,
            )
            .order_by("-created_at")
            .first()
        )


class PersonalSummary(BaseModel):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, help_text="Patient this summary is about")
    body = models.TextField(blank=True, help_text="Generated HTML content")
    summary_type: models.Field[PersonalSummaryType, PersonalSummaryType] = EnumField(
        PersonalSummaryType,
        default=PersonalSummaryType.HEALTH_SUMMARY,
        help_text="The type of personal summary generated",
    )

    objects = PersonalSummaryManager()

    class Meta:
        verbose_name_plural = "PersonalSummaries"

    def __str__(self) -> str:
        return f"{self.get_summary_type_display()} - {self.patient.full_name}"
