import factory.random
from faker.providers import BaseProvider


class ImmunizationProvider(BaseProvider):
    __provider__ = "immunization_name"

    def immunization_name(self):
        return factory.random.randgen.choice(immunization_names)


immunization_names = [
    "AS03 Adjuvant",
    "ActHIB",
    "Agrippal",
    "Avaxim",
    "BCG",
    "Bacillus Calmette-Guerin vaccine",
    "CDT",
    "COMVAX",
    "DTPa",
    "DTaP-hepatitis B and poliovirus vaccine",
    "Diphtheria",
    "Ebola, unspecified",
    "Engerix B",
    "Fluarix",
    "Fluvax Junior",
    "Fluvax",
    "Fluvirin",
    "HBV",
    "HBVAX II",
    "HIB",
    "HPV, unspecified formulation",
    "Havrix Junior",
    "Hep A, live attenuated-IM",
    "Hepatitis A immune globulin",
    "Hepatitis A",
    "Hepatitis B",
    "HibTITER",
    "Hiberix",
    "Human Papillomavirus 9-valent vaccine",
    "IPOL",
    "Infanrix Hexa",
    "Infanrix Penta",
    "Infanrix",
    "Infanrix-IPV",
    "InfanrixHepB",
    "Influenza",
    "Influenza, seasonal, injectable",
    "Influvac",
    "JE-VAX",
    "Japanese Encephalitis Vaccine SC",
    "Japanese Encephalitis",
    "Junin virus vaccine",
    "Lyme disease vaccine",
    "MMR II",
    "MMR",
    "Measles",
    "Mencevax ACWY",
    "Meningitec",
    "Meningococcal C",
    "Menitorix",
    "Menjugate",
    "Menomune",
    "Mumps",
    "NeisVac-C",
    "Novel influenza-H1N1-09, injectable",
    "Panvax",
    "Pediacel",
    "PedvaxHIB",
    "Pertussis",
    "Pneumococcal",
    "Pneumovax",
    "Poliacel",
    "Polio",
    "Prevenar 13",
    "Prevenar 7",
    "Priorix",
    "Priorix-Tetra",
    "ProHIBit",
    "ProQuad",
    "Q fever vaccine",
    "Quadracel",
    "Rho(D) Immune globulin - IM",
    "Rho(D) Immune globulin- IV or IM",
    "Rho(D) Unspecified formulation",
    "Rift Valley fever vaccine",
    "Rotarix",
    "Rotateq",
    "Rotavirus",
    "Rubella",
    "Staphylococcus bacteriophage lysate",
    "Synflorix",
    "Td(adult) unspecified formulation",
    "Tetanus",
    "Tripacel",
    "Triple Antigen",
    "Twinrix Junior",
    "Typhoid conjugate vaccine (non-US)",
    "Vaqta Paed/Adol",
    "Varicella",
    "Varilrix",
    "Varivax",
    "Vaxigrip Junior",
    "Vaxigrip",
    "adenovirus vaccine, type 4, live, oral",
    "adenovirus vaccine, type 7, live, oral",
    "anthrax immune globulin",
    "anthrax vaccine",
    "botulinum antitoxin",
    "cholera, BivWC",
    "cholera, WC-rBS",
    "cholera, live attenuated",
    "dengue fever vaccine",
    "diphtheria antitoxin",
    "hantavirus vaccine",
    "hepatitis A and hepatitis B vaccine",
    "hepatitis A vaccine, adult dosage",
    "hepatitis B immune globulin",
    "hepatitis B vaccine, adult dosage",
    "hepatitis C vaccine",
    "hepatitis E vaccine",
    "herpes simplex virus, type 2 vaccine",
    "human immunodeficiency virus vaccine",
    "human papilloma virus vaccine, bivalent",
    "immune globulin, intramuscular",
    "immune globulin, intravenous",
    "influenza virus vaccine, whole virus",
    "leishmaniasis vaccine",
    "leprosy vaccine",
    "malaria vaccine",
    "measles and rubella virus vaccine",
    "measles virus vaccine",
    "melanoma vaccine",
    "meningococcal C conjugate vaccine",
    "mumps virus vaccine",
    "no vaccine administered",
    "parainfluenza-3 virus vaccine",
    "pertussis vaccine",
    "plague vaccine",
    "poliovirus vaccine, inactivated",
    "rabies immune globulin",
    "rabies vaccine, unspecified formulation",
    "rheumatic fever vaccine",
    "rotavirus, live, monovalent vaccine",
    "rotavirus, live, pentavalent vaccine",
    "rotavirus, live, tetravalent vaccine",
    "rubella and mumps virus vaccine",
    "rubella virus vaccine",
    "tetanus immune globulin",
    "tetanus toxoid, adsorbed",
    "tetanus toxoid, not adsorbed",
    "tetanus toxoid, unspecified formulation",
    "tick-borne encephalitis vaccine",
    "tularemia vaccine",
    "typhoid vaccine, live, oral",
    "unknown vaccine or immune globulin",
    "vaccinia (smallpox) vaccine",
    "vaccinia (smallpox) vaccine, diluted",
    "vaccinia immune globulin",
    "varicella virus vaccine",
    "varicella zoster immune globulin",
    "yellow fever vaccine",
    "zoster vaccine recombinant",
    "zoster vaccine, live",
    "zoster vaccine, unspecified formulation",
]
